---
title: "Modern Climate"
author: "Nick Gauthier"
date: "6/7/2017"
output: 
  html_document: 
    highlight: pygments
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Present Day Climate in North Africa
```{r message=F, warning=F}
library(raster)
library(tidyverse)
library(ClimClass)
library(parallel)
```

Define the study area
```{r}
bbox <- extent(-10, 20, 28, 38)
```

Download WorldClim data.
```{r}
prec <- getData('worldclim', var = 'prec', res = 2.5) %>%
  crop(bbox)

tmin <- getData('worldclim', var = 'tmin', res = 2.5) %>%
  crop(bbox) %>%
  `/`(10)

tmax <- getData('worldclim', var = 'tmax', res = 2.5) %>%
  crop(bbox) %>%
  `/`(10)
```

Write a function wrapping the koeppen_geiger function from ClimClass to make the mapping easier.
```{r}
koeppen_map <- function(x){
  ifelse(is.na(prec[x][1]), 
         return(NA),
      return(data_frame(month = 1:12,
           P = c(prec[x]),
           Tx = c(tmax[x]),
           Tn = c(tmin[x])) %>%
    mutate(Tm = (Tx + Tn) / 2) %>%
    koeppen_geiger(clim.resume_verbose = F) %>%
    .$class %>%
    as.character))
}
```

Run the climate classification in parallel to speed things up.
```{r}
clim_class <- mclapply(1:ncell(prec), koeppen_map, mc.cores = detectCores()) %>% 
  unlist %>%
  as.factor %>%
  setValues(prec[[1]], .)
```

Plot the results.
```{r}
clim_class %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  mutate(class = recode_factor(prec1_VALUE, BSh = 'Hot semi-arid',
  BSk = 'Cold semi-arid',
  BWh = 'Hot desert',
  BWk = 'Cold desrt',
  Csa = 'Hot-summer Mediterranean',
  Csb = 'Warm-summer Mediterranean',
  Dsb = 'Warm, dry-summer continental',
  Dsc = 'Dry-summer subarctic')) %>%
  ggplot(aes(x, y, fill = class)) +
  geom_raster() +
  labs(title = 'Present day climate of North Africa', subtitle = 'Based on WorldClim data') +
  scale_fill_discrete(name = 'Köppen-Geiger classification') +
  theme_void() +
  coord_quickmap()
```